### ISSUE TITLE
NO SOUND 

### ISSUE THREAD

**Issue by Vijaykv5** [3kh0/soundboard#1]
There is no sound for the many rows especially the below ones

**Comment by 3kh0** [comment]
Can you provide console logs?

**Comment by ThatOnePers0n** [comment]
> There is no sound for the many rows especially the below ones

Can confirm, having the same issue

**Comment by ThatOnePers0n** [comment]
> Can you provide console logs?

On mobile, can't currently

**Comment by 3kh0** [comment]
Stale
